### ISSUE TITLE
Docker startup can cause ArchivesSpace to run in a failure state indefinitely

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1456]
If you run a `docker-compose up` or a `docker stack deploy` for a stack that contains an ArchivesSpace service along with a MySQL Service, where

1. ArchivesSpace is not built from source,
2. ArchivesSpace does not have a deploy package, and 
3. ArchivesSpace does not have any plugins to initialize,

then the ArchivesSpace service typically gets to the `setup-database.sh` script before the MySQL service is ready to accept connections. This causes the database setup script to fail, but the failure does not cause the container to exit. Instead, the docker-startup.sh will move on to running `archivesspace.sh`, which will continuously fail forever, until the service or container is either restarted, or the mysql database is set up manually.

## Expected Behavior

It seems that Docker services typically exit whenever there is a failure in the Docker container prior to the execution of the app itself, sometimes including failures with the app itself. If the container fails in this way, it allows the Docker daemon to determine if the service needs to be restarted, depending on the service's configured restart policy. This allows you to rely on Docker a little bit when designing Docker startup scripts. Automatic service restarts are turned on by default for Docker stacks, and can be enabled for docker-compose stacks.

docker-compose: https://docs.docker.com/compose/compose-file/#restart
docker stack: https://docs.docker.com/compose/compose-file/#restart_policy

## Current Behavior

If `/archivesspace/scripts/setup-database.sh` is reached before the mysql service is ready to accept connections, then the database will never be set up or migrated. This means you have to perform some sort of manual step when starting ArchivesSpace using the default `docker-startup.sh`.

1. Start the `db` service first, then wait for a bit, then start the `archivesspace` service.
2. Watch the logs of the `db` service, then restart the `archivesspace` service once the `db` service is ready for connections.

## Possible Solution

I'm putting in a pull request to add in a hard failure for db connection issues when running the db setup script, which I will link shortly. This PR adds an exit status check after the database setup script, which will echo and then exit if the database setup fails, identical to what's currently happening if `wget`ing the `ASPACE_DEPLOY_PKG_URL` fails.

An alternative to this would be to add a `set -e` to the top of the Docker startup script, which would be a little more invasive change and would prevent the startup script from being able to echo a message to the logs when a failure is detected.

## Steps to Reproduce

This happens for both `docker-compose` workflows, as well as `docker stack deploy` workflows.

```yml
version: '3.2'
services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123

  archivesspace:
    image: archivesspace/archivesspace:2.5.2
    environment:
      APPCONFIG_DB_URL: "jdbc:mysql://db:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123"      
    depends_on:
      - db
```

## Context

I'm starting to spin up production instances of ArchivesSpace as Docker containers, as part of an automated deployment pipeline. I also spin up new local instances of ArchivesSpace for testing and migration purposes, sometimes multiple times a day. It would be nice if I could just `docker-compose up -d` or `docker stack deploy` and walk away for a while, without having to worry about ArchivesSpace getting stuck or requiring manual attention.

I have been using some workarounds to address for a while, but I figured it might be time to put in an issue and a pull request.

## Environment

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
