### ISSUE TITLE
Unclear documentation on Docker Container

### ISSUE THREAD

**Issue by Dr-Crow** [archivesspace/archivesspace#1495]
I am trying to setup Archives Space via docker for production use but there seems to be a lack of documentation for it. 

When I pull down the docker container from [Dockerhub](https://hub.docker.com/r/archivesspace/archivesspace) there is no information on environment variables I need to set. As it currently stands, if i run the docker container Archives Spaces tells me what I am running the demo database and it should not be used in production. 

From digging around in this repo I see that you have a docker compose file, which is helpful, but no where in the documentation does it mention this. Additionally, none if the environment variables are documented in there, so I have very little to go off of. 

Right now, I am testing out my docker compose file with just `APPCONFIG_DB_URL` set, but I would love to know what the other environment variables are and what they do. It seems that to just get Archives Space up and running I need the DB URL.

Is there a plan moving forward to document this setup and if so can I contribute? 

Here is my docker file for reference: 

```
  database:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123
    restart: always
    volumes:
      - /volume1/docker/mysql-archivesspace:/var/lib/mysql
  archivesspace:
    image: archivesspace/archivesspace:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
    depends_on:
      - database
    environment:
      APPCONFIG_DB_URL: 'jdbc:mysql://database:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123'
      # disable the embedded solr
      # testing plugin initialization on startup
      #ASPACE_INITIALIZE_PLUGINS: 'newrelic'
    links:
      - database

```

**Comment by AustinTSchaffer** [comment]
Hey @Dr-Crow,

Is the MySQL DB connection now working that you have set the DB_URL in your configuration?

At any rate, I forget when and where I figured the following information out, but you can find some information on which environment variables are used in from looking at [the docker-startup.sh script](https://github.com/archivesspace/archivesspace/blob/master/docker-startup.sh):

- `APPCONFIG_DATA_DIR`: Allows you to specify an alternative location for what typically goes in the `/archivesspace/data` directory.
- `ASPACE_DEPLOY_PKG_URL`: Allows you to specifies a ZIP archive that is downloaded when the container is started, which can contain a `config.rb`, a `plugins/` directory, and a `stylesheets/` directory.
- `ASPACE_INITIALIZE_PLUGINS`: Allows you to specify a comma-separated list of plugins to initialize on startup.

I personally do not use any of these, in favor of distributing plugins and managing the data directory by using Docker mounts and Docker volumes with local files, but they give you a little flexibility. Beyond that, you can override most `AppConfig` settings using environment variables. You can only specify boolean, integer, or string values through environment variables, unfortunately, but any `AppConfig` setting that accepts one of those value types can be used.

How overriding AppConfig settings with environment variables works: https://github.com/archivesspace/archivesspace/blob/bc675bc12b72f6fb7818aae646958c80d54ff4de/common/config/config-distribution.rb#L72
Defaults for AppConfig settings: https://github.com/archivesspace/archivesspace/blob/bc675bc12b72f6fb7818aae646958c80d54ff4de/common/config/config-defaults.rb

Personally, I only ever use `APPCONFIG_FRONTEND_URL`, `APPCONFIG_PUBLIC_URL`, `APPCONFIG_DB_URL`, and `APPCONFIG_INDEXER_LOG_LEVEL` (to reduce log spam). If I'm ever configuring something more complicated, I'll typically mount my own `config.rb`:

```rb
services:
  # ...
  aspace:
    # ...
    volumes:
      - ./aspace/config.rb:/archivesspace/config/config.rb
```

Hope this helps,
Austin

**Comment by Dr-Crow** [comment]
@AustinTSchaffer thanks so much! Hands down, this was the most helpful response. Yes, with adding the DB_URL my docker compose file now works. 

So if I understand everything you saying, I should be able to find all the configurable variables in [config-defaults.rb](https://github.com/archivesspace/archivesspace/blob/bc675bc12b72f6fb7818aae646958c80d54ff4de/common/config/config-defaults.rb). For example if I wanted to change the `max_page_size`, I could set the environment variable in my docker compose file like, `APPCONFIG_MAX_PAGE_SIZE=10`.

You mentioned you have a couple other docker volume mounts, do you mind sharing what your storing in your setup? Do you store `/archivesspace/data` in a volume mount?

As for the `config.rb`, that is a good tip for having it stored as a mount. Do you suggest that over setting a bunch of environment variables in the docker compose file? 

Additionally, looking at your dockerhub pages were extremely helpful when trying to figure out how to get mine up and going. Have you thought submitting a pull request to update some of the official documentation on Archives Space?

**Comment by AustinTSchaffer** [comment]
> Hands down, this was the most helpful response.

:100: :100: :100: :champagne: :1st_place_medal: :100: :100: :100:

> For example if I wanted to change the `max_page_size`, I could set the environment variable in my docker compose file like, `APPCONFIG_MAX_PAGE_SIZE=10`

It looks like that would work. I've never really tried any environment variables other than the 4 that I've mentioned, but I don't see a reason why it wouldn't.

> You mentioned you have a couple other docker volume mounts, do you mind sharing what your storing in your setup? Do you store /archivesspace/data in a volume mount?

Sure thing. So, I originally tried mounting the data directory to a local directory, but I was having permissions issues with that kind of setup. Instead, I store `/archivesspace/data` as a Docker volume. Deleting the indexes can be annoying in this configuration (if you care about the non-index data in the data directory, you have to do something like `docker container exec -it <archivesspace-container> rm /archivesspace/data/index*`, or `docker container exec <etc etc etc> /bin/sh` and clear out what I need to, then `docker container restart <archivesspace-container>`).

Sample docker-compose configuration: https://gist.github.com/AustinTSchaffer/4f2a3ad4dd27097ed8bf25be4f12453b

> As for the config.rb, that is a good tip for having it stored as a mount. Do you suggest that over setting a bunch of environment variables in the docker compose file?

If you're setting a bunch of environment variables (more than I don't know, 4?), then I would definitely recommend using a mounted `config.rb`. It's the traditional way to configure ArchivesSpace, so it's easier to find documentation and specify valid configurations. For example, I always use a mounted config when configuring a plugin. Otherwise, I don't really manage production ArchivesSpace instances running in Docker (currently), so the env var configurations work just fine for what I need them to do.

> Additionally, looking at your dockerhub pages were extremely helpful when trying to figure out how to get mine up and going. Have you thought submitting a pull request to update some of the official documentation on Archives Space?

Unfortunately, you can't update Docker hub descriptions with a pull request, so I haven't submitted any issues or PRs for that. At this point, I typically just read the issues board and source code when I'm looking for how something works, and I'll submit changes if the documentation doesn't match how the product actually works. Feel free to reach out if you have any questions though!

**Comment by AustinTSchaffer** [comment]
@Dr-Crow ,

I was looking through Docker documentation on secrets and came across a better way to mount configs into an ArchivesSpace container. Thought you might find it interesting.

https://docs.docker.com/compose/compose-file/#configs

Best,
Austin

**Comment by mark-cooper** [comment]
@Dr-Crow Docker isn't an "officially" supported deployment option for ArchivesSpace by the Program Team, that's why there isn't a lot of documentation for it. However as you've found Docker is being used in various contexts.

"Is there a plan moving forward to document this setup and if so can I contribute?"

I don't believe there's a plan to add more documentation aimed at supporting Docker as an "endorsed" deployment option, because the Program Team is focused on development of the software more than support for deployment tooling. Having said that if you have the time and interest adding to the tech docs for Docker would be welcomed:

https://github.com/archivesspace/tech-docs/blob/master/development/docker.md

**Comment by Dr-Crow** [comment]
@mark-cooper Thanks for the input and clarification. Do you guys have a road map and if so do you have a rough time of when Docker support and other forms of development will be supported?

@AustinTSchaffer Thanks for all your help. I know you mentioned you ran into permission issues with mounts. Did you ever solve this issue? Or did you just use docker  volumes inside of the docker compose file?

From my understanding those docker compose volumes not actually map to the file system in any meaningful way. Thus I wanted to use mounts.

```
  archivesspace:
    image: archivesspace/archivesspace:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
    depends_on:
      - database
    restart: always
    environment:
      APPCONFIG_DB_URL: 'jdbc:mysql://database:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123'
    links:
      - database
    volumes:
      - /volume1/docker/data-archivesspace:/archivesspace/data
      - /volume1/docker/config-archivesspace:/archivesspace/config
      - /volume1/docker/plugins-archivesspace:/archivesspace/plugins
```

I had the above in my docker compose file and it causes all sorts of issue with the install. I had to remove `/volume1/docker/config-archivesspace:/archivesspace/config` to get it to boot. Which I think was cause it did not have a `config.rb`. But even with that removed I now run into a permission issue with `/archivesspace/data` folder. 

Ideally, I want the data folder mounted to my file system so I can do backups and upgrade without loosing data. 

Also I would love to chat more about what you been doing with ArchivesSpaces with your organization.
