### ISSUE TITLE
SESSION_GONE error due to batch import taking over an hour

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1562]
As part of an Archivists' Toolkit migration, I'm using the `batch_imports` API endpoint to attach thousands of Archival Object records to individual Resource records. One POST in particular uploaded a JSON array of 5186 archival object records to be attached to a single resource. Based on the output of my client-side logs, it appears that my client waited 1.18 hours (over 4200 seconds) while the data sent to the `batch_imports` endpoint was processed by the ArchivesSpace backend.

Since the POST was initiated close to the end of its current hour (4:58), 2 expiry jobs (5:00 and 6:00) ran in between the POST initiating (4:58) and the POST completing (6:09). This caused the session to be deleted by the "expiry" cron-job while my client was waiting for the batch process to complete.

I've attached the relevant logs from my client along with the backend logs, showing what the ASpace backend was doing in between 4:58 and 6:09. My configuration for the migration is only running the aspace backed, so nothing was deleted from the middle of the timeframe that I provided. I've also included a link to the method that is referenced in the stack trace of my client logs, if anyone is interested.

[backend_logs.log](https://github.com/archivesspace/archivesspace/files/3139460/backend_logs.log)

[client_logs.log](https://github.com/archivesspace/archivesspace/files/3139461/client_logs.log)

https://github.com/AustinTSchaffer/aspace_migrator/blob/8fad1421b2e77dffecf87bcdedd944bfd9bb8502/aspace_migrator/migration_components/resources.py#L66

## Expected Behavior

Since my client had no idle time and was just waiting for the response for the full 1.18 hours, I would have expected that my session would not expire while I waited for the API to respond. Since the result of the HTTP post was "ok" (no timeout, no data errors), I would have expected that the very next post would work as well.

## Current Behavior

https://github.com/archivesspace/archivesspace/blob/9295321ad1da909b53b9dfc2b202856421ad5a30/backend/app/main.rb#L245

Since the session is touched at the beginning of a batch import and not the end, its possible for the session to be considered "expired" and even deleted, while the batch import is processing.

## Possible Solution(s)

Would it be possible to expedite the batch import endpoint? I was using it to hopefully cut down on log-noise by creating one HTTP POST instead of 5000+ individual HTTP POSTs, but it does appear that the ASpace backend took about 0.82 seconds to process each Archival Object record. It might be faster and easier in the long-run to just post the records individually.

Would it be possible to execute `session.touch` and/or `Session.initialize` in `RequestWrappingMiddleware.call` after the result is created, as well as before?

Would there be some other way to "lock" a session id so it cannot be flagged as expired or deleted, while the request is being processed?

Would it be possible to set up batch imports as a "background job", allowing me to upload the batch import data and then effectively walk away, so I can move on to the next batch import?

My workarounds are to set the session expiration time to "1 week" for my migration ASpace instance configuration, and to look into incorporating "reauthenticate and replay the HTTP method if the result was SESSION_EXPIRED or SESSION_GONE" into my ArchivesSpace API client. I'd also like to start using async/await for my migration code, but the process has worked before and I'm not interested in making all of that more efficient at this time.

## Steps to Reproduce (for bugs)

This bug will be a bit annoying to replicate exactly, since it involves the expiry cron that only runs on the hour and cannot be configured to run more regularly (without a code change). I've included some sample steps, but they're basically the same as testing whether or not deleting a session prevents any future actions from being able to use the session token.

1. Set up ArchivesSpace
2. Using a Python REPL or a REST client (Insomnia or Postman) or anything else as long as you can log in to the API as "admin" and get a session token.
3. Simulate a long-running batch POST (do nothing)
4. Simulate a cron cleanup (MySQL `delete from session;`)
5. Try an authenticated HTTP method (GET/DELETE/POST) using the old auth token

## Context

Trying to migrate AT data to ASpace and mildly annoyed that ArchivesSpace cleared my session while I was actively using it. Rude.

## Your Environment

Docker-Compose file containing my ArchivesSpace configuration for my migration workflow. The migration job also runs in a container, so you may need to expose port 8089 for any tests.

```yml
version: '3.2'
services:

  db:
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123
    volumes:
      - aspace_data:/var/lib/mysql

  aspace:
    image: archivesspace/archivesspace:2.5.2
    environment:
      APPCONFIG_DB_URL: "jdbc:mysql://db:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123"
      APPCONFIG_ENABLE_BACKEND: "true"
      APPCONFIG_ENABLE_FRONTEND: "false"
      APPCONFIG_ENABLE_PUBLIC: "false"
      APPCONFIG_ENABLE_DOCS: "false"
      APPCONFIG_ENABLE_INDEXER: "false"
      APPCONFIG_ENABLE_SOLR: "false"
      # The setting below is my workaround.
      # APPCONFIG_SESSION_EXPIRE_AFTER_SECONDS: 604800
    depends_on:
      - db

volumes:
  aspace_data:
```
