### ISSUE TITLE
Regression with PUI Proxying

### ISSUE THREAD

**Issue by AustinTSchaffer** [archivesspace/archivesspace#1623]
Appears to be related to https://github.com/archivesspace/archivesspace/issues/957.

For my local ArchivesSpace setups, I have been reverse-proxying the PUI, frontend, and the API. It appears to be something broke sometime between v2.5.2 and v2.6.0, because the PUI is having proxying issues that aren't in v2.5.2.

## Setup

For testing this regression, I have 2 instances of ArchivesSpace running on the same host. One of the AS instances is v2.5.2 and the other is v2.6.0, with the following minimal configurations in a docker-compose file:

```yml
version: '3.3'

services:
  aspace_252:
    image: archivesspace/archivesspace:2.5.2
    environment:
      APPCONFIG_FRONTEND_PROXY_URL: "/as252/staff/"
      APPCONFIG_PUBLIC_PROXY_URL: "/as252/"
    volumes:
      - ./as252_data:/archivesspace/data

  aspace_260:
    image: archivesspace/archivesspace:2.6.0
    environment:
      APPCONFIG_FRONTEND_PROXY_URL: "/as260/staff/"
      APPCONFIG_PUBLIC_PROXY_URL: "/as260/"
    volumes:
      - ./as260_data:/archivesspace/data
```

These 2 instances of ArchivesSpace are proxied using the following routes:

```
"/as252/" -> "http://aspace_252:8081"
"/as252/staff/" -> "http://aspace_252:8080"
"/as252/api/" -> "http://aspace_252:8089"
"/as260/" -> "http://aspace_260:8081"
"/as260/staff/" -> "http://aspace_260:8080"
"/as260/api/" -> "http://aspace_260:8089"
```

These 2 instances have minimal data, both having the a single identical repository and a single identical resource.

## Behavior

The staff interface looks correct between the 2 instances, but font-awsome is broken in the PUI only on v2.6.0. Looks fine in v2.5.2. Also, some links in the v2.6.0 PUI do not have the proxy prefix.

## Screenshots

Comparison between AS v2.5.2 and AS v2.6.0, showing broken fonts in AS v2.6.0. For the v2.6.0 instance, using `fa-regular-400.woff2` as an example, the browser attempts to load the resource as `http://localhost/as260/assets/font-awesome//fa-regular-400.woff2`, which is redirected to `http://localhost/as260/assets/font-awesome/fa-regular-400.woff2`, which gives a 404. 

![image](https://user-images.githubusercontent.com/16184219/61406596-27f84700-a8aa-11e9-8ed6-cc1095bce0ff.png)

Proxied repository links in AS v2.5.2 are correct.

![image](https://user-images.githubusercontent.com/16184219/61406887-cbe1f280-a8aa-11e9-95ce-e1bf500929d1.png)

Proxied repository links in AS v2.6.0 are not correct. (Only on the "Repositories" page, apparently. Seems to work fine everywhere else)

![image](https://user-images.githubusercontent.com/16184219/61406798-92a98280-a8aa-11e9-8efd-349d6a84afed.png)
